# src/interfaces/llm_interface.py
from abc import ABC, abstractmethod

class ILlmInterface(ABC):
    """
    Abstract Base Class for LLM interaction.
    This ensures that whether we use Ollama, OpenAI, or HuggingFace,
    the rest of the app calls the exact same method.
    """

    @abstractmethod
    def generate_code(self, system_prompt: str, user_prompt: str) -> str:
        """
        Generates code based on a system context and user request.
        
        Args:
            system_prompt: The 'Role' and 'Rules' (e.g., "You are an expert engineer...").
            user_prompt: The specific request (e.g., "Create a scenario where...").
            
        Returns:
            str: The raw Python code string generated by the AI.
        """
        pass